package cn.xisun.mybatis.mbg.entity;

import lombok.ToString;

@ToString
public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_name
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.sex
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.age
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.dep_id
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    private Long depId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_name
     *
     * @return the value of employee.emp_name
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_name
     *
     * @param empName the value for employee.emp_name
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.sex
     *
     * @return the value of employee.sex
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.sex
     *
     * @param sex the value for employee.sex
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.age
     *
     * @return the value of employee.age
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.age
     *
     * @param age the value for employee.age
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.dep_id
     *
     * @return the value of employee.dep_id
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    public Long getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.dep_id
     *
     * @param depId the value for employee.dep_id
     *
     * @mbg.generated Tue Jul 26 15:12:28 CST 2022
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }
}